#!/usr/bin/env python3
"""
auto_hotstart.py  (rendered per run directory by setup_run.py)
==============================================================
Self-contained SCHISM monthly run manager for ONE run directory.

This file is generated by the stofs_ak_workflow package for each
R{ID}_YYYYMM/ run directory. The constants in the CONFIG block below are
filled in at setup time; do not edit them by hand.

Behaviour (ihot=1, single end-of-month hotstart):
  1. Submit run_test (the SCHISM MPI job) via sbatch.
  2. Poll squeue:
       - if the job is RUNNING, watch outputs/mirror.out for advancement and
         detect hangs (no time-step progress);
       - if the job DISAPPEARS from the queue, check whether the run finished
         ("Run completed successfully" in mirror.out).
     A crashed / time-limited / hung run is simply re-submitted from the
     original hotstart.nc (there are NO intermediate hotstarts: param.nml is
     written so SCHISM outputs exactly one hotstart at the last timestep).
  3. On successful completion:
       - submit run_comb (combine_hotstart7.exe -i NHOT_WRITE) inside outputs/;
       - wait for it to finish and verify outputs/hotstart_it=NHOT_WRITE.nc;
       - if this is NOT the last month and chaining is enabled, symlink that
         combined hotstart as NEXT_RUNDIR/hotstart.nc and launch the next
         month's auto_hotstart.py (blocking);
       - write the run.done sentinel and exit.

The package's submit_run step calls this script with the run directory as the
current working directory and blocks until it returns.
"""

import os
import re
import sys
import time
import subprocess
from datetime import datetime
from pathlib import Path


# ============================ CONFIG (filled by setup_run) ============================
RUNDIR         = r"{{RUNDIR}}"          # absolute path to this run directory
NEXT_RUNDIR    = {{NEXT_RUNDIR}}        # absolute path (str) to next month, or None
CHAIN_HOTSTART = {{CHAIN_HOTSTART}}     # True/False: auto-chain to next month
IS_LAST_MONTH  = {{IS_LAST_MONTH}}      # True for the final month
NHOT_WRITE     = {{NHOT_WRITE}}         # timestep at which the hotstart is written
MONTH          = r"{{MONTH}}"           # YYYYMM label (for messages)
RUN_JOBNAME    = r"{{RUN_JOBNAME}}"     # e.g. R01_01  (matches run_test -J)
POLL_SECONDS   = {{POLL_SECONDS}}       # polling interval (seconds)
# =====================================================================================

QUEUE_CMD = f"squeue -u {os.environ.get('USER', os.environ.get('LOGNAME', ''))}"


def log(msg):
    print(f"[{datetime.now():%Y-%m-%d %H:%M:%S}] {msg}", flush=True)


def sh(cmd):
    """Run a shell command, return (rc, stdout)."""
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    return r.returncode, r.stdout.strip()


def squeue_line_for(jobname):
    """Return the squeue line for our job name, or None if not present."""
    _, out = sh(QUEUE_CMD)
    pat = re.compile(rf"\b{re.escape(jobname)}\b")
    for line in out.splitlines():
        if pat.search(line):
            return line.strip()
    return None


def submit(script):
    """sbatch a script from RUNDIR; return the job id string."""
    rc, out = sh(f"sbatch {script}")
    if rc != 0:
        log(f"ERROR: sbatch {script} failed:\n{out}")
        sys.exit(1)
    log(out)
    # "Submitted batch job 12345"
    return out.split()[-1]


def mirror_last_line():
    mo = Path(RUNDIR) / "outputs" / "mirror.out"
    if not mo.exists():
        return None
    try:
        lines = mo.read_text(errors="ignore").splitlines()
    except Exception:
        return None
    return lines[-1] if lines else None


def mirror_time_step():
    """Return the most recent 'TIME STEP' value in mirror.out (or None)."""
    mo = Path(RUNDIR) / "outputs" / "mirror.out"
    if not mo.exists():
        return None
    try:
        lines = mo.read_text(errors="ignore").splitlines()
    except Exception:
        return None
    for line in reversed(lines):
        m = re.search(r"TIME STEP\s*=?\s*(\d+)", line)
        if m:
            return int(m.group(1))
    return None


def run_completed():
    last = mirror_last_line()
    return last is not None and "Run completed successfully" in last


def combine_and_chain():
    """Submit run_comb, wait, verify the combined hotstart, then chain."""
    combined = Path(RUNDIR) / "outputs" / f"hotstart_it={NHOT_WRITE}.nc"

    if not combined.exists():
        comb_jobname = "C" + RUN_JOBNAME[1:]  # R01_01 -> C01_01
        log(f"Submitting run_comb to build {combined.name} ...")
        submit("run_comb")
        # Wait for the combine job to leave the queue.
        while squeue_line_for(comb_jobname) is not None:
            log("  waiting for combine job to finish ...")
            time.sleep(POLL_SECONDS)
        time.sleep(10)
        if not combined.exists():
            log(f"ERROR: combine finished but {combined} was not created.")
            sys.exit(1)
    else:
        log(f"{combined.name} already exists; skipping combine.")

    log(f"End-of-month hotstart ready: {combined}")

    # Chain to the next month.
    if IS_LAST_MONTH:
        log("This is the last month; no chaining.")
    elif not CHAIN_HOTSTART:
        log("chain_hotstart=false; not launching the next month.")
    elif NEXT_RUNDIR is None:
        log("No next run directory configured; not chaining.")
    else:
        next_hot = Path(NEXT_RUNDIR) / "hotstart.nc"
        if next_hot.exists() or next_hot.is_symlink():
            next_hot.unlink()
        next_hot.symlink_to(combined)
        log(f"Symlinked next month's hotstart: {next_hot} -> {combined}")

    # Sentinel BEFORE launching the next month, so this month is marked done
    # even if the next month is still running.
    (Path(RUNDIR) / "run.done").touch()
    log(f"Wrote sentinel: {Path(RUNDIR) / 'run.done'}")

    if (not IS_LAST_MONTH) and CHAIN_HOTSTART and NEXT_RUNDIR is not None:
        next_script = Path(NEXT_RUNDIR) / "auto_hotstart.py"
        if not next_script.exists():
            log(f"ERROR: {next_script} not found; run setup_run for the next month.")
            sys.exit(1)
        log(f"Launching next month: {next_script}")
        # Blocking: the whole chain runs nested. When this returns, all
        # downstream months are complete.
        r = subprocess.run([sys.executable, str(next_script)], cwd=str(NEXT_RUNDIR))
        if r.returncode != 0:
            log(f"ERROR: next month ({NEXT_RUNDIR}) failed (exit {r.returncode}).")
            sys.exit(r.returncode)


def main():
    os.chdir(RUNDIR)
    log(f"=== auto_hotstart for {MONTH}  ({RUNDIR}) ===")
    log(f"run job name: {RUN_JOBNAME}   combine step: {NHOT_WRITE}")

    if (Path(RUNDIR) / "run.done").exists():
        log("run.done already present; nothing to do.")
        return

    if not (Path(RUNDIR) / "hotstart.nc").exists():
        log("ERROR: hotstart.nc not found in run directory.")
        log("  Month 1 expects a symlink to I{ID}_{first}/hotstart.nc (created by")
        log("  setup_run); later months expect the previous month to have chained it.")
        sys.exit(1)

    # Submit the initial run.
    submit("run_test")
    previous_step = -1

    while not run_completed():
        time.sleep(POLL_SECONDS)
        print(f"\n{'%'*72}\n  {datetime.now():%Y-%m-%d %H:%M:%S}\n{'%'*72}")
        status = squeue_line_for(RUN_JOBNAME)
        _, full = sh(QUEUE_CMD)
        print(full)

        if status is not None:
            job_id = re.search(r"\b\d+\b", status)
            job_id = job_id.group() if job_id else "?"
            if re.search(rf"{re.escape(RUN_JOBNAME)}\s+\S+\s+R", status):
                # RUNNING — hang detection.
                time.sleep(60)
                step = mirror_time_step()
                if step is None:
                    log(f"{RUN_JOBNAME}: running but mirror.out has no TIME STEP yet.")
                elif step == previous_step:
                    log(f"{RUN_JOBNAME}: HANG detected at TIME STEP {step}; cancelling.")
                    sh(f"scancel {job_id}")
                    # Loop will find the job gone, see the run is incomplete,
                    # and resubmit from the original hotstart.
                else:
                    log(f"{RUN_JOBNAME}: advancing, TIME STEP {step}.")
                    previous_step = step
            else:
                log(f"{RUN_JOBNAME}: queued (job {job_id}), waiting ...")
        else:
            # Not in queue. Either finished successfully or stopped early.
            if run_completed():
                break
            previous_step = -1
            log(f"{RUN_JOBNAME}: not in queue and run incomplete — resubmitting "
                f"from hotstart.nc (full month re-run).")
            submit("run_test")

    log(f"{RUN_JOBNAME}: run completed successfully.")
    combine_and_chain()
    log(f"=== auto_hotstart for {MONTH} done ===")


if __name__ == "__main__":
    main()
