#!/usr/bin/env python3
"""
auto_hotstart.py  (rendered per run directory by setup_run.py)
==============================================================
Self-contained SCHISM monthly run manager for ONE run directory.

This file is generated by the stofs_ak_workflow package for each
R{ID}_YYYYMM/ run directory. The constants in the CONFIG block below are
filled in at setup time; do not edit them by hand.

Behaviour (ihot=1, single end-of-month hotstart):
  1. Submit run_test (the SCHISM MPI job) via sbatch.
  2. Poll squeue:
       - if the job is RUNNING, watch outputs/mirror.out for advancement and
         detect hangs (no time-step progress);
       - if the job DISAPPEARS from the queue, check whether the run finished
         ("Run completed successfully" in mirror.out).
     A crashed / time-limited / hung run is simply re-submitted from the
     original hotstart.nc (there are NO intermediate hotstarts: param.nml is
     written so SCHISM outputs exactly one hotstart at the last timestep).
  3. On successful completion:
       - (UFS-SCHISM only) run combine_output11_MPI to combine per-rank output
         stacks into global daily files, then delete the partition-specific files;
       - submit run_comb (combine_hotstart7.exe -i NHOT_WRITE) inside outputs/;
       - wait for it to finish and verify outputs/hotstart_it=NHOT_WRITE.nc;
       - delete per-rank hotstart files (hotstart_00*.nc) to free disk;
       - if this is NOT the last month and chaining is enabled, symlink that
         combined hotstart as NEXT_RUNDIR/hotstart.nc and launch the next
         month's auto_hotstart.py (blocking);
       - write the run.done sentinel and exit.

The package's submit_run step calls this script with the run directory as the
current working directory and blocks until it returns.
"""

import os
import re
import sys
import time
import subprocess
from datetime import datetime
from pathlib import Path


# ============================ CONFIG (filled by setup_run) ============================
RUNDIR         = r"{{RUNDIR}}"          # absolute path to this run directory
NEXT_RUNDIR    = {{NEXT_RUNDIR}}        # absolute path (str) to next month, or None
CHAIN_HOTSTART = {{CHAIN_HOTSTART}}     # True/False: auto-chain to next month
IS_LAST_MONTH  = {{IS_LAST_MONTH}}      # True for the final month
NHOT_WRITE     = {{NHOT_WRITE}}         # timestep at which the hotstart is written
MONTH          = r"{{MONTH}}"           # YYYYMM label (for messages)
RUN_JOBNAME    = r"{{RUN_JOBNAME}}"     # e.g. R01_01  (matches run_test -J)

# --- diagnostic-plot hook (Phase 5 diag_run_plots, dispatched during the run) ---
DIAG_ENABLED        = {{DIAG_ENABLED}}
DIAG_SBATCH         = r"{{DIAG_SBATCH}}"
DIAG_VARS_MANIFEST  = r"{{DIAG_VARS_MANIFEST}}"
DIAG_NVAR           = {{DIAG_NVAR}}

# --- combine_output11_MPI hook (UFS-SCHISM old I/O only) ---
# When enabled, after the run completes successfully:
#   1. mpirun combine_output11_MPI -b 1 -e <nstacks> combines all per-rank
#      schout_NNNNNN_*.nc files into global schout_*.nc daily files.
#   2. Per-rank partition files (schout_NNNNNN_*.nc) are deleted to free disk.
# For SCHISM standalone (New I/O) set this to False.
COMBINE_OUTPUT_ENABLED  = {{COMBINE_OUTPUT_ENABLED}}   # True for UFS-SCHISM, False for SCHISM
COMBINE_OUTPUT_EXE      = r"{{COMBINE_OUTPUT_EXE}}"    # e.g. ./outputs/combine_output11_MPI
COMBINE_OUTPUT_NRANKS   = {{COMBINE_OUTPUT_NRANKS}}    # MPI ranks for combine job
COMBINE_OUTPUT_SBATCH   = r"{{COMBINE_OUTPUT_SBATCH}}" # path to rendered run_combine_output sbatch
# =====================================================================================

# Adaptive polling schedule (seconds between status checks).
_POLL_SCHEDULE = [
    0,       # check immediately after submit
    60,      # +1 min
    60,      # +2 min
    60,      # +3 min
    60,      # +4 min
    60,      # +5 min
    300,     # +10 min
    1200,    # +30 min
    1800,    # +60 min
]
_POLL_STEADY = 1800  # 30 min between checks once schedule is exhausted

_COMBINE_POLL_SECONDS = 60
_MAX_RESUBMITS = 5


def _poll_sleep(poll_iter: int):
    if poll_iter < len(_POLL_SCHEDULE):
        secs = _POLL_SCHEDULE[poll_iter]
    else:
        secs = _POLL_STEADY
    if secs > 0:
        time.sleep(secs)


QUEUE_CMD = f"squeue -u {os.environ.get('USER', os.environ.get('LOGNAME', ''))}"


def log(msg):
    print(f"[{datetime.now():%Y-%m-%d %H:%M:%S}] {msg}", flush=True)


def sh(cmd):
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    combined = (r.stdout.strip() + "\n" + r.stderr.strip()).strip()
    return r.returncode, combined


def squeue_line_for(jobname):
    _, out = sh(QUEUE_CMD)
    pat = re.compile(rf"\b{re.escape(jobname)}\b")
    for line in out.splitlines():
        if pat.search(line):
            return line.strip()
    return None


def _clean_outputs():
    """Delete stale output stacks and mirror.out before (re)submitting SCHISM."""
    outdir = Path(RUNDIR) / "outputs"
    deleted = []

    for f in sorted(outdir.glob("*_*.nc")):
        if f.name.startswith("hotstart_it="):
            continue
        if re.search(r"_\d+$", f.stem):
            f.unlink()
            deleted.append(f.name)

    mirror = outdir / "mirror.out"
    if mirror.exists():
        mirror.unlink()
        deleted.append("mirror.out")

    if deleted:
        log(f"Cleaned {len(deleted)} stale file(s) from outputs/ before submission:")
        for name in deleted:
            log(f"  deleted: {name}")
    else:
        log("outputs/ is clean (no stale stacks or mirror.out to remove).")


def submit(script):
    rc, out = sh(f"sbatch {script}")
    if rc != 0:
        log(f"ERROR: sbatch {script} failed:\n{out}")
        sys.exit(1)
    log(out)
    return out.split()[-1]


def mirror_last_line():
    mo = Path(RUNDIR) / "outputs" / "mirror.out"
    if not mo.exists():
        return None
    try:
        lines = mo.read_text(errors="ignore").splitlines()
    except Exception:
        return None
    return lines[-1] if lines else None


def mirror_time_step():
    mo = Path(RUNDIR) / "outputs" / "mirror.out"
    if not mo.exists():
        return None
    try:
        lines = mo.read_text(errors="ignore").splitlines()
    except Exception:
        return None
    for line in reversed(lines):
        m = re.search(r"TIME STEP\s*=?\s*(\d+)", line)
        if m:
            return int(m.group(1))
    return None


def run_completed():
    mo = Path(RUNDIR) / "outputs" / "mirror.out"
    if not mo.exists():
        return False
    try:
        lines = mo.read_text(errors="ignore").splitlines()
    except Exception:
        return False
    for line in reversed(lines[-25:]):
        if "Run completed successfully" in line:
            return True
    return False


# --- diagnostic-plot dispatch ---
_diag_submitted = set()


def dispatch_diag_plots(run_finished: bool = False):
    if not DIAG_ENABLED or not DIAG_SBATCH:
        return
    outdir = Path(RUNDIR) / "outputs"
    stacks = sorted(
        (int(p.stem.split("_")[1]) for p in outdir.glob("out2d_*.nc")),
    )
    if not stacks:
        return
    max_stack = max(stacks)
    for n in stacks:
        if n in _diag_submitted:
            continue
        is_complete = (n < max_stack) or run_finished
        if not is_complete:
            continue
        rc, out = sh(
            f"sbatch --export=ALL,DIAG_MONTH={MONTH},DIAG_STACK={n} "
            f"{DIAG_SBATCH}"
        )
        if rc == 0:
            log(f"diag_run_plots: submitted stack {n} array 1-{DIAG_NVAR}  ({out})")
            _diag_submitted.add(n)
        else:
            log(f"diag_run_plots: sbatch FAILED for stack {n}: {out}")


def job_exit_code(job_id: str) -> int:
    rc, out = sh(f"sacct -n -X -o ExitCode -j {job_id}")
    if rc != 0 or not out.strip():
        return -1
    for token in out.strip().splitlines():
        token = token.strip()
        if token:
            try:
                return int(token.split(":")[0])
            except ValueError:
                return -1
    return -1


def diagnose_failure(job_id: str) -> str:
    fe = Path(RUNDIR) / "outputs" / "fatal.error"
    if fe.exists():
        txt = fe.read_text(errors="ignore").strip()
        if txt:
            return f"SCHISM fatal.error:\n{txt}"

    err_log = Path(RUNDIR) / "err2.out"
    if err_log.exists():
        lines = err_log.read_text(errors="ignore").splitlines()
        diag = [l for l in lines
                if any(k in l for k in ("forrtl:", "ABORT", "srun: error",
                                        "severe", "error (78)"))]
        if diag:
            snippet = "\n".join(diag[:6])
            return f"Fortran/MPI error in err2.out:\n{snippet}"

    myout = Path(RUNDIR) / "myout"
    if myout.exists():
        for line in myout.read_text(errors="ignore").splitlines():
            if "ABORT" in line:
                return f"ABORT in myout: {line.strip()}"

    code = job_exit_code(job_id)
    if code > 0:
        return f"Job {job_id} exited with non-zero code {code} (no further details found)."

    return ""


def _clean_partition_hotstarts():
    """Delete per-rank hotstart files after the combined hotstart is built."""
    outdir = Path(RUNDIR) / "outputs"
    pat = re.compile(r"^hotstart_\d+_\d+\.nc$")
    deleted = 0
    freed = 0
    for f in sorted(outdir.glob("hotstart_*.nc")):
        if f.name.startswith("hotstart_it="):
            continue
        if pat.match(f.name):
            try:
                freed += f.stat().st_size
            except OSError:
                pass
            f.unlink(missing_ok=True)
            deleted += 1
    if deleted:
        log(f"Deleted {deleted} per-rank hotstart file(s) "
            f"(~{freed / 1e9:.1f} GB freed); kept the combined hotstart.")


def _partition_hotstarts_exist():
    outdir = Path(RUNDIR) / "outputs"
    pat = re.compile(rf"^hotstart_\d+_{NHOT_WRITE}\.nc$")
    return any(pat.match(f.name)
               for f in outdir.glob(f"hotstart_*_{NHOT_WRITE}.nc"))


# =============================================================================
# combine_output11_MPI — UFS-SCHISM old I/O only
# =============================================================================

def _count_output_stacks() -> int:
    """Count the number of schout stacks written this month.

    Looks for schout_000000_N.nc files (rank-0 files) in outputs/ to determine
    how many stacks were written. Returns 0 if none found.
    """
    outdir = Path(RUNDIR) / "outputs"
    stacks = set()
    for f in outdir.glob("schout_000000_*.nc"):
        m = re.search(r"schout_000000_(\d+)\.nc$", f.name)
        if m:
            stacks.add(int(m.group(1)))
    return max(stacks) if stacks else 0


def _clean_output_partition_files():
    """Delete per-rank schout partition files after successful combination.

    Deletes schout_NNNNNN_*.nc files (rank-specific) while preserving the
    combined schout_*.nc files (no rank prefix). Also deletes
    local_to_global_* files which are no longer needed after combination.

    MUST be called only after combination has been verified successful.
    """
    outdir = Path(RUNDIR) / "outputs"

    # Per-rank schout files: schout_000000_1.nc, schout_003193_2.nc, etc.
    # Pattern: schout_ followed by exactly 6 digits, then underscore, then digits
    pat_schout = re.compile(r"^schout_\d{6}_\d+\.nc$")
    deleted_schout = 0
    freed_schout = 0
    for f in sorted(outdir.glob("schout_??????_*.nc")):
        if pat_schout.match(f.name):
            try:
                freed_schout += f.stat().st_size
            except OSError:
                pass
            f.unlink(missing_ok=True)
            deleted_schout += 1

    # local_to_global_* mapping files (needed by combine_output11_MPI but
    # not after combination is complete)
    deleted_l2g = 0
    freed_l2g = 0
    for f in sorted(outdir.glob("local_to_global_*")):
        try:
            freed_l2g += f.stat().st_size
        except OSError:
            pass
        f.unlink(missing_ok=True)
        deleted_l2g += 1

    total_freed = (freed_schout + freed_l2g) / 1e9
    log(f"Deleted {deleted_schout} per-rank schout file(s) and "
        f"{deleted_l2g} local_to_global file(s) "
        f"(~{total_freed:.1f} GB freed).")


def combine_output_stacks():
    """Run combine_output11_MPI to combine per-rank output stacks.

    Submits run_combine_output (a SLURM job) that runs combine_output11_MPI
    with mpirun to process all stacks written this month. Waits for completion,
    verifies the combined files exist, then deletes the partition-specific files.

    This function is only called when COMBINE_OUTPUT_ENABLED is True
    (UFS-SCHISM old I/O). For SCHISM standalone (New I/O) this is skipped.

    Sentinel: outputs/combine_output.done
    """
    if not COMBINE_OUTPUT_ENABLED:
        return

    outdir = Path(RUNDIR) / "outputs"
    sentinel = outdir / "combine_output.done"

    if sentinel.exists():
        log("combine_output: already complete (sentinel found). Skipping.")
        _clean_output_partition_files()
        return

    nstacks = _count_output_stacks()
    if nstacks == 0:
        log("WARNING: combine_output: no schout_000000_*.nc stacks found. "
            "Skipping output combination.")
        return

    log(f"combine_output: combining {nstacks} stack(s) with "
        f"{COMBINE_OUTPUT_NRANKS} MPI rank(s) ...")

    # Submit the combine job and wait for it to finish
    comb_jobname = "CO" + RUN_JOBNAME[1:]   # R02_01 -> CO02_01
    rc, out = sh(
        f"sbatch --export=ALL,"
        f"COMBINE_BEGIN=1,COMBINE_END={nstacks},"
        f"COMBINE_JOBNAME={comb_jobname} "
        f"{COMBINE_OUTPUT_SBATCH}"
    )
    if rc != 0:
        log(f"ERROR: sbatch {COMBINE_OUTPUT_SBATCH} failed:\n{out}")
        sys.exit(1)
    log(f"Submitted combine_output job: {out}")

    # Wait for combine job to leave the queue
    while squeue_line_for(comb_jobname) is not None:
        log(f"  waiting for combine_output job ({comb_jobname}) to finish ...")
        time.sleep(_COMBINE_POLL_SECONDS)
    time.sleep(10)

    # Verify combined files exist (one schout_N.nc per stack, no rank prefix)
    missing = []
    for i in range(1, nstacks + 1):
        combined_f = outdir / f"schout_{i}.nc"
        if not combined_f.exists() or combined_f.stat().st_size == 0:
            missing.append(combined_f.name)

    if missing:
        log(f"ERROR: combine_output finished but {len(missing)} combined "
            f"file(s) are missing or empty:")
        for m in missing[:10]:
            log(f"  {m}")
        log("Check the combine_output log for errors. "
            "Per-rank files are preserved for retry.")
        sys.exit(1)

    log(f"combine_output: all {nstacks} stack(s) combined successfully.")
    sentinel.touch()

    # Delete per-rank partition files now that combination is verified
    _clean_output_partition_files()


def combine_and_chain():
    """Submit run_comb, wait, verify the combined hotstart, then chain."""
    combined = Path(RUNDIR) / "outputs" / f"hotstart_it={NHOT_WRITE}.nc"
    if not combined.exists():
        comb_jobname = "C" + RUN_JOBNAME[1:]  # R01_01 -> C01_01
        log(f"Submitting run_comb to build {combined.name} ...")
        submit("run_comb")
        while squeue_line_for(comb_jobname) is not None:
            log("  waiting for combine job to finish ...")
            time.sleep(_COMBINE_POLL_SECONDS)
        time.sleep(10)
        if not combined.exists():
            log(f"ERROR: combine finished but {combined} was not created.")
            sys.exit(1)
    else:
        log(f"{combined.name} already exists; skipping combine.")

    log(f"End-of-month hotstart ready: {combined}")

    # Delete per-rank hotstart files to free disk
    _clean_partition_hotstarts()

    # Chain to the next month
    if IS_LAST_MONTH:
        log("This is the last month; no chaining.")
    elif not CHAIN_HOTSTART:
        log("chain_hotstart=false; not launching the next month.")
    elif NEXT_RUNDIR is None:
        log("No next run directory configured; not chaining.")
    else:
        next_hot = Path(NEXT_RUNDIR) / "hotstart.nc"
        if next_hot.exists() or next_hot.is_symlink():
            next_hot.unlink()
        next_hot.symlink_to(combined)
        log(f"Symlinked next month's hotstart: {next_hot} -> {combined}")

    (Path(RUNDIR) / "run.done").touch()
    log(f"Wrote sentinel: {Path(RUNDIR) / 'run.done'}")

    if (not IS_LAST_MONTH) and CHAIN_HOTSTART and NEXT_RUNDIR is not None:
        next_script = Path(NEXT_RUNDIR) / "auto_hotstart.py"
        if not next_script.exists():
            log(f"ERROR: {next_script} not found; run setup_run for the next month.")
            sys.exit(1)
        log(f"Launching next month: {next_script}")
        r = subprocess.run([sys.executable, str(next_script)], cwd=str(NEXT_RUNDIR))
        if r.returncode != 0:
            log(f"ERROR: next month ({NEXT_RUNDIR}) failed (exit {r.returncode}).")
            sys.exit(r.returncode)


def main():
    os.chdir(RUNDIR)
    log(f"=== auto_hotstart for {MONTH}  ({RUNDIR}) ===")
    log(f"run job name: {RUN_JOBNAME}   combine step: {NHOT_WRITE}")

    if (Path(RUNDIR) / "run.done").exists():
        log("run.done already present; nothing to do.")
        return

    if not (Path(RUNDIR) / "hotstart.nc").exists():
        log("ERROR: hotstart.nc not found in run directory.")
        log("  Month 1 expects a symlink to I{ID}_{first}/hotstart.nc (created by")
        log("  setup_run); later months expect the previous month to have chained it.")
        sys.exit(1)

    combined = Path(RUNDIR) / "outputs" / f"hotstart_it={NHOT_WRITE}.nc"
    if run_completed() and (combined.exists() or _partition_hotstarts_exist()):
        log(f"Run already complete; end-of-month hotstart present "
            f"(combined={combined.exists()}, "
            f"per-rank={_partition_hotstarts_exist()}). "
            f"Skipping SCHISM re-run and proceeding to combine/chain.")
        dispatch_diag_plots(run_finished=True)
        combine_output_stacks()
        combine_and_chain()
        log(f"=== auto_hotstart for {MONTH} done ===")
        return

    # Submit the initial run
    _clean_outputs()
    job_id = submit("run_test")
    previous_step = -1
    poll_iter = 0
    resubmit_count = 0

    while not run_completed():
        _poll_sleep(poll_iter)
        poll_iter += 1
        print(f"\n{'%'*72}\n  {datetime.now():%Y-%m-%d %H:%M:%S}  "
              f"(poll #{poll_iter})\n{'%'*72}")
        status = squeue_line_for(RUN_JOBNAME)
        _, full = sh(QUEUE_CMD)
        print(full)

        dispatch_diag_plots(run_finished=run_completed())

        if status is not None:
            m = re.search(r"\b\d+\b", status)
            job_id = m.group() if m else job_id
            if re.search(rf"{re.escape(RUN_JOBNAME)}\s+\S+\s+R", status):
                if poll_iter >= 4:
                    step = mirror_time_step()
                    if step is None:
                        log(f"{RUN_JOBNAME}: running but mirror.out has no TIME STEP yet.")
                    elif step == previous_step:
                        log(f"{RUN_JOBNAME}: HANG detected at TIME STEP {step}; cancelling.")
                        sh(f"scancel {job_id}")
                    else:
                        log(f"{RUN_JOBNAME}: advancing, TIME STEP {step}.")
                        previous_step = step
                else:
                    log(f"{RUN_JOBNAME}: running (job {job_id}), early poll — skipping hang check.")
            else:
                log(f"{RUN_JOBNAME}: queued (job {job_id}), waiting ...")
        else:
            if run_completed():
                break

            diag = diagnose_failure(job_id if job_id != "?" else "0")
            exit_code = job_exit_code(job_id if job_id != "?" else "0")

            if diag:
                log("ERROR: SCHISM run failed with a non-recoverable error.")
                log("Do NOT resubmit until the problem is fixed.")
                log("Details:")
                for line in diag.splitlines()[:12]:
                    log(f"  {line}")
                log(f"SLURM output log: {Path(RUNDIR) / 'myout'}")
                log(f"SLURM error log:  {Path(RUNDIR) / 'err2.out'}")
                log(f"SCHISM abort:     {Path(RUNDIR) / 'outputs' / 'fatal.error'}")
                log("Fix the input, then re-run:")
                log("  stofs-ak --run --phase run --only submit_run --config <cfg>")
                sys.exit(1)

            if exit_code > 0:
                log(f"WARNING: job {job_id} exited with code {exit_code} and "
                    f"no diagnostic detail was found.")
                log("This is likely a time-limit, node failure, or OOM.")
                resubmit_count += 1
                if resubmit_count > _MAX_RESUBMITS:
                    log(f"ERROR: max resubmit limit ({_MAX_RESUBMITS}) reached. Exiting.")
                    sys.exit(1)
                log(f"Resubmitting (attempt {resubmit_count}/{_MAX_RESUBMITS}).")
                previous_step = -1
                _clean_outputs()
                submit("run_test")
                continue

            previous_step = -1
            resubmit_count += 1
            if resubmit_count > _MAX_RESUBMITS:
                log(f"ERROR: max resubmit limit ({_MAX_RESUBMITS}) reached. Exiting.")
                sys.exit(1)
            log(f"{RUN_JOBNAME}: not in queue and run incomplete — resubmitting "
                f"(attempt {resubmit_count}/{_MAX_RESUBMITS}).")
            _clean_outputs()
            submit("run_test")

    log(f"{RUN_JOBNAME}: run completed successfully.")
    dispatch_diag_plots(run_finished=True)
    combine_output_stacks()
    combine_and_chain()
    log(f"=== auto_hotstart for {MONTH} done ===")


if __name__ == "__main__":
    main()
