#!/usr/bin/env python3
"""
auto_hotstart.py  (rendered per run directory by setup_run.py)
==============================================================
Self-contained SCHISM monthly run manager for ONE run directory.

This file is generated by the stofs_ak_workflow package for each
R{ID}_YYYYMM/ run directory. The constants in the CONFIG block below are
filled in at setup time; do not edit them by hand.

Behaviour (ihot=1, single end-of-month hotstart):
  1. Submit run_test (the SCHISM MPI job) via sbatch.
  2. Poll squeue:
       - if the job is RUNNING, watch outputs/mirror.out for advancement and
         detect hangs (no time-step progress);
       - if the job DISAPPEARS from the queue, check whether the run finished
         ("Run completed successfully" in mirror.out).
     A crashed / time-limited / hung run is simply re-submitted from the
     original hotstart.nc (there are NO intermediate hotstarts: param.nml is
     written so SCHISM outputs exactly one hotstart at the last timestep).
  3. On successful completion:
       - submit run_comb (combine_hotstart7.exe -i NHOT_WRITE) inside outputs/;
       - wait for it to finish and verify outputs/hotstart_it=NHOT_WRITE.nc;
       - if this is NOT the last month and chaining is enabled, symlink that
         combined hotstart as NEXT_RUNDIR/hotstart.nc and launch the next
         month's auto_hotstart.py (blocking);
       - write the run.done sentinel and exit.

The package's submit_run step calls this script with the run directory as the
current working directory and blocks until it returns.
"""

import os
import re
import sys
import time
import subprocess
from datetime import datetime
from pathlib import Path


# ============================ CONFIG (filled by setup_run) ============================
RUNDIR         = r"{{RUNDIR}}"          # absolute path to this run directory
NEXT_RUNDIR    = {{NEXT_RUNDIR}}        # absolute path (str) to next month, or None
CHAIN_HOTSTART = {{CHAIN_HOTSTART}}     # True/False: auto-chain to next month
IS_LAST_MONTH  = {{IS_LAST_MONTH}}      # True for the final month
NHOT_WRITE     = {{NHOT_WRITE}}         # timestep at which the hotstart is written
MONTH          = r"{{MONTH}}"           # YYYYMM label (for messages)
RUN_JOBNAME    = r"{{RUN_JOBNAME}}"     # e.g. R01_01  (matches run_test -J)

# --- diagnostic-plot hook (Phase 5 diag_run_plots, dispatched during the run) ---
DIAG_ENABLED        = {{DIAG_ENABLED}}       # True/False: submit diag_run jobs for new stacks
DIAG_SBATCH         = r"{{DIAG_SBATCH}}"     # path to the rendered diag_run.sbatch (or "")
DIAG_VARS_MANIFEST  = r"{{DIAG_VARS_MANIFEST}}"  # one var_name per line; used by the array
DIAG_NVAR           = {{DIAG_NVAR}}          # number of variables (= array size)
# =====================================================================================

# Adaptive polling schedule (seconds between status checks).
# Polls frequently right after job submission, then backs off.
# After the schedule is exhausted, polls every 3600 s (1 hour) indefinitely.
_POLL_SCHEDULE = [
    0,       # check immediately after submit
    60,      # +1 min
    60,      # +2 min
    60,      # +3 min
    60,      # +4 min
    60,      # +5 min
    300,     # +10 min
    1200,    # +30 min
    1800,    # +60 min
]
_POLL_STEADY = 3600  # 1 hour between checks once schedule is exhausted

# Seconds between checks while waiting for the run_comb (combine_hotstart) job
# to leave the queue.
_COMBINE_POLL_SECONDS = 60


def _poll_sleep(poll_iter: int):
    """Sleep the appropriate amount for this poll iteration."""
    if poll_iter < len(_POLL_SCHEDULE):
        secs = _POLL_SCHEDULE[poll_iter]
    else:
        secs = _POLL_STEADY
    if secs > 0:
        time.sleep(secs)

QUEUE_CMD = f"squeue -u {os.environ.get('USER', os.environ.get('LOGNAME', ''))}"


def log(msg):
    print(f"[{datetime.now():%Y-%m-%d %H:%M:%S}] {msg}", flush=True)


def sh(cmd):
    """Run a shell command, return (rc, stdout+stderr combined)."""
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    combined = (r.stdout.strip() + "\n" + r.stderr.strip()).strip()
    return r.returncode, combined


def squeue_line_for(jobname):
    """Return the squeue line for our job name, or None if not present."""
    _, out = sh(QUEUE_CMD)
    pat = re.compile(rf"\b{re.escape(jobname)}\b")
    for line in out.splitlines():
        if pat.search(line):
            return line.strip()
    return None


def _clean_outputs():
    """Delete stale output stacks and mirror.out before (re)submitting SCHISM.

    When SCHISM restarts from hotstart.nc it always writes from stack 1.
    Any *_N.nc output files left over from a previous run attempt (e.g. after
    an HPC outage, wall-time kill, or hang) have a time axis that starts
    mid-month, causing SCHISM to abort with 'fill_header_static: time dim'
    when it tries to open those files at startup.

    mirror.out is also removed so that run_completed() and mirror_time_step()
    don't read stale state from the previous attempt.

    hotstart_it=<N>.nc is explicitly preserved — it is the combined end-of-month
    hotstart and must survive if it was already written.
    """
    outdir = Path(RUNDIR) / "outputs"
    deleted = []

    # Numbered output stacks: out2d_1.nc, temperature_2.nc, etc.
    # Pattern: any file matching *_<digits>.nc that is NOT hotstart_it=*.nc
    for f in sorted(outdir.glob("*_*.nc")):
        if f.name.startswith("hotstart_it="):
            continue
        # Only match files whose stem ends with _<digits>
        if re.search(r"_\d+$", f.stem):
            f.unlink()
            deleted.append(f.name)

    # mirror.out — written by SCHISM, not overwritten by SLURM on resubmit
    mirror = outdir / "mirror.out"
    if mirror.exists():
        mirror.unlink()
        deleted.append("mirror.out")

    if deleted:
        log(f"Cleaned {len(deleted)} stale file(s) from outputs/ before submission:")
        for name in deleted:
            log(f"  deleted: {name}")
    else:
        log("outputs/ is clean (no stale stacks or mirror.out to remove).")


def submit(script):
    """sbatch a script from RUNDIR; return the job id string."""
    rc, out = sh(f"sbatch {script}")
    if rc != 0:
        log(f"ERROR: sbatch {script} failed:\n{out}")
        sys.exit(1)
    log(out)
    # "Submitted batch job 12345"
    return out.split()[-1]


def mirror_last_line():
    mo = Path(RUNDIR) / "outputs" / "mirror.out"
    if not mo.exists():
        return None
    try:
        lines = mo.read_text(errors="ignore").splitlines()
    except Exception:
        return None
    return lines[-1] if lines else None


def mirror_time_step():
    """Return the most recent 'TIME STEP' value in mirror.out (or None)."""
    mo = Path(RUNDIR) / "outputs" / "mirror.out"
    if not mo.exists():
        return None
    try:
        lines = mo.read_text(errors="ignore").splitlines()
    except Exception:
        return None
    for line in reversed(lines):
        m = re.search(r"TIME STEP\s*=?\s*(\d+)", line)
        if m:
            return int(m.group(1))
    return None


def run_completed():
    """True if mirror.out contains SCHISM's completion banner.

    SCHISM (schism_finalize.F90) writes 'Run completed successfully at ...'
    near the very end of fort.16/mirror.out. Under scribe I/O a few trailing
    lines may follow it, so scan the LAST several lines rather than only the
    final one.
    """
    mo = Path(RUNDIR) / "outputs" / "mirror.out"
    if not mo.exists():
        return False
    try:
        lines = mo.read_text(errors="ignore").splitlines()
    except Exception:
        return False
    for line in reversed(lines[-25:]):
        if "Run completed successfully" in line:
            return True
    return False


# --- diagnostic-plot dispatch (diag_run_plots) --------------------------------
_diag_submitted = set()   # stacks already handed to a diag_run job


def dispatch_diag_plots(run_finished: bool = False):
    """Submit diag_run job arrays for newly-completed output stacks.

    A stack out2d_N.nc is 'complete' once out2d_{N+1}.nc exists (SCHISM writes
    stacks sequentially), or — for the final stack — once the run has finished.
    Called on each poll when DIAG_ENABLED. Idempotent: each stack is submitted
    at most once (tracked in _diag_submitted; each per-variable diag job also
    writes its own diag_{N}_{varname}.done sentinel).

    One SLURM job array is submitted per stack: array size = DIAG_NVAR (one
    task per configured variable). Tasks run in parallel so the wall-time is
    that of a single variable, not all variables combined.
    """
    if not DIAG_ENABLED or not DIAG_SBATCH:
        return
    outdir = Path(RUNDIR) / "outputs"
    stacks = sorted(
        (int(p.stem.split("_")[1]) for p in outdir.glob("out2d_*.nc")),
    )
    if not stacks:
        return
    max_stack = max(stacks)
    for n in stacks:
        if n in _diag_submitted:
            continue
        # Complete if a later stack exists, or the run has finished.
        is_complete = (n < max_stack) or run_finished
        if not is_complete:
            continue
        # Submit the job array for stack n.
        # Note: --array is already set in the rendered diag_run.sbatch header
        # (#SBATCH --array=1-N). Do NOT pass --array on the command line too —
        # SLURM rejects submissions where the same directive appears both in
        # the script and on the command line.
        rc, out = sh(
            f"sbatch --export=ALL,DIAG_MONTH={MONTH},DIAG_STACK={n} "
            f"{DIAG_SBATCH}"
        )
        if rc == 0:
            log(f"diag_run_plots: submitted stack {n} array 1-{DIAG_NVAR}  ({out})")
            _diag_submitted.add(n)
        else:
            log(f"diag_run_plots: sbatch FAILED for stack {n}: {out}")


def job_exit_code(job_id: str) -> int:
    """Query sacct for the exit code of a completed SLURM job.

    Returns the integer exit code, or -1 if sacct is unavailable or the
    job is not found (treated as unknown/pending).
    A non-zero code means the job exited abnormally (Fortran error, OOM,
    signal, etc.) and should NOT be blindly resubmitted.
    """
    rc, out = sh(f"sacct -n -X -o ExitCode -j {job_id}")
    if rc != 0 or not out.strip():
        return -1
    # sacct ExitCode field is "exit_code:signal" e.g. "19:0" or "0:0"
    # Take the first non-empty token and split on ':'
    for token in out.strip().splitlines():
        token = token.strip()
        if token:
            try:
                return int(token.split(":")[0])
            except ValueError:
                return -1
    return -1


def diagnose_failure(job_id: str) -> str:
    """Return a human-readable failure description for a crashed job.

    Checks (in order):
      1. outputs/fatal.error  — SCHISM-written abort file
      2. err2.out             — SBATCH -e log (Fortran/MPI stack traces)
      3. myout                — SBATCH -o log (ABORT keyword scan)
      4. sacct exit code      — non-zero means a crash of some kind

    Returns a string describing the failure, or an empty string if nothing
    definitive is found (caller should still not resubmit if exit code != 0).
    """
    # 1. SCHISM fatal.error
    fe = Path(RUNDIR) / "outputs" / "fatal.error"
    if fe.exists():
        txt = fe.read_text(errors="ignore").strip()
        if txt:
            return f"SCHISM fatal.error:\n{txt}"

    # 2. Fortran/MPI error in err2.out (SBATCH -e)
    err_log = Path(RUNDIR) / "err2.out"
    if err_log.exists():
        lines = err_log.read_text(errors="ignore").splitlines()
        # Look for "forrtl:", "ABORT", "srun: error" as diagnostic lines
        diag = [l for l in lines
                if any(k in l for k in ("forrtl:", "ABORT", "srun: error",
                                        "severe", "error (78)"))]
        if diag:
            snippet = "\n".join(diag[:6])
            return f"Fortran/MPI error in err2.out:\n{snippet}"

    # 3. ABORT keyword in myout (SBATCH -o)
    myout = Path(RUNDIR) / "myout"
    if myout.exists():
        for line in myout.read_text(errors="ignore").splitlines():
            if "ABORT" in line:
                return f"ABORT in myout: {line.strip()}"

    # 4. Fall back to exit code
    code = job_exit_code(job_id)
    if code > 0:
        return f"Job {job_id} exited with non-zero code {code} (no further details found)."

    return ""


def combine_and_chain():
    """Submit run_comb, wait, verify the combined hotstart, then chain."""
    combined = Path(RUNDIR) / "outputs" / f"hotstart_it={NHOT_WRITE}.nc"

    if not combined.exists():
        comb_jobname = "C" + RUN_JOBNAME[1:]  # R01_01 -> C01_01
        log(f"Submitting run_comb to build {combined.name} ...")
        submit("run_comb")
        # Wait for the combine job to leave the queue.
        while squeue_line_for(comb_jobname) is not None:
            log("  waiting for combine job to finish ...")
            time.sleep(_COMBINE_POLL_SECONDS)
        time.sleep(10)
        if not combined.exists():
            log(f"ERROR: combine finished but {combined} was not created.")
            sys.exit(1)
    else:
        log(f"{combined.name} already exists; skipping combine.")

    log(f"End-of-month hotstart ready: {combined}")

    # Chain to the next month.
    if IS_LAST_MONTH:
        log("This is the last month; no chaining.")
    elif not CHAIN_HOTSTART:
        log("chain_hotstart=false; not launching the next month.")
    elif NEXT_RUNDIR is None:
        log("No next run directory configured; not chaining.")
    else:
        next_hot = Path(NEXT_RUNDIR) / "hotstart.nc"
        if next_hot.exists() or next_hot.is_symlink():
            next_hot.unlink()
        next_hot.symlink_to(combined)
        log(f"Symlinked next month's hotstart: {next_hot} -> {combined}")

    # Sentinel BEFORE launching the next month, so this month is marked done
    # even if the next month is still running.
    (Path(RUNDIR) / "run.done").touch()
    log(f"Wrote sentinel: {Path(RUNDIR) / 'run.done'}")

    if (not IS_LAST_MONTH) and CHAIN_HOTSTART and NEXT_RUNDIR is not None:
        next_script = Path(NEXT_RUNDIR) / "auto_hotstart.py"
        if not next_script.exists():
            log(f"ERROR: {next_script} not found; run setup_run for the next month.")
            sys.exit(1)
        log(f"Launching next month: {next_script}")
        # Blocking: the whole chain runs nested. When this returns, all
        # downstream months are complete.
        r = subprocess.run([sys.executable, str(next_script)], cwd=str(NEXT_RUNDIR))
        if r.returncode != 0:
            log(f"ERROR: next month ({NEXT_RUNDIR}) failed (exit {r.returncode}).")
            sys.exit(r.returncode)


def main():
    os.chdir(RUNDIR)
    log(f"=== auto_hotstart for {MONTH}  ({RUNDIR}) ===")
    log(f"run job name: {RUN_JOBNAME}   combine step: {NHOT_WRITE}")

    if (Path(RUNDIR) / "run.done").exists():
        log("run.done already present; nothing to do.")
        return

    if not (Path(RUNDIR) / "hotstart.nc").exists():
        log("ERROR: hotstart.nc not found in run directory.")
        log("  Month 1 expects a symlink to I{ID}_{first}/hotstart.nc (created by")
        log("  setup_run); later months expect the previous month to have chained it.")
        sys.exit(1)

    # Short-circuit: if the SCHISM run already completed AND the combined
    # end-of-month hotstart already exists, skip re-running the whole month
    # and go straight to combine_and_chain(). This handles the case where a
    # previous invocation finished the run and built the hotstart but crashed
    # before writing run.done / chaining (e.g. an interrupted combine/chain
    # stage). combine_and_chain() is idempotent: it detects the existing
    # hotstart, symlinks it into the next month, writes run.done, and chains.
    combined = Path(RUNDIR) / "outputs" / f"hotstart_it={NHOT_WRITE}.nc"
    if combined.exists() and run_completed():
        log(f"Run already complete and {combined.name} exists; "
            f"skipping SCHISM re-run and proceeding to combine/chain.")
        combine_and_chain()
        log(f"=== auto_hotstart for {MONTH} done ===")
        return

    # Submit the initial run.
    _clean_outputs()
    job_id = submit("run_test")
    previous_step = -1
    poll_iter = 0

    while not run_completed():
        _poll_sleep(poll_iter)
        poll_iter += 1
        elapsed_mins = sum(_POLL_SCHEDULE[:min(poll_iter, len(_POLL_SCHEDULE))]) // 60
        if poll_iter > len(_POLL_SCHEDULE):
            elapsed_mins += (poll_iter - len(_POLL_SCHEDULE)) * _POLL_STEADY // 60
        print(f"\n{'%'*72}\n  {datetime.now():%Y-%m-%d %H:%M:%S}  "
              f"(poll #{poll_iter})\n{'%'*72}")
        status = squeue_line_for(RUN_JOBNAME)
        _, full = sh(QUEUE_CMD)
        print(full)

        # Fire diagnostic plots for any newly-completed output stacks.
        dispatch_diag_plots(run_finished=run_completed())

        if status is not None:
            m = re.search(r"\b\d+\b", status)
            job_id = m.group() if m else job_id  # update job_id when visible
            if re.search(rf"{re.escape(RUN_JOBNAME)}\s+\S+\s+R", status):
                # RUNNING — hang detection.
                # Only check for hangs from poll 4 onward (give the run time
                # to start writing mirror.out before declaring it hung).
                if poll_iter >= 4:
                    step = mirror_time_step()
                    if step is None:
                        log(f"{RUN_JOBNAME}: running but mirror.out has no TIME STEP yet.")
                    elif step == previous_step:
                        log(f"{RUN_JOBNAME}: HANG detected at TIME STEP {step}; cancelling.")
                        sh(f"scancel {job_id}")
                        # Loop will find the job gone, diagnose or resubmit.
                    else:
                        log(f"{RUN_JOBNAME}: advancing, TIME STEP {step}.")
                        previous_step = step
                else:
                    log(f"{RUN_JOBNAME}: running (job {job_id}), early poll — skipping hang check.")
            else:
                log(f"{RUN_JOBNAME}: queued (job {job_id}), waiting ...")
        else:
            # Not in queue. Either finished successfully or stopped early.
            if run_completed():
                break

            # Diagnose the failure before deciding whether to resubmit.
            # job_id may be None if the job never appeared in the poll loop
            # (e.g. it started and finished between polls). Use "?" as a
            # fallback — sacct will return nothing and we fall back to file checks.
            diag = diagnose_failure(job_id if job_id != "?" else "0")
            exit_code = job_exit_code(job_id if job_id != "?" else "0")

            if diag:
                log("ERROR: SCHISM run failed with a non-recoverable error.")
                log("Do NOT resubmit until the problem is fixed.")
                log("Details:")
                for line in diag.splitlines()[:12]:
                    log(f"  {line}")
                log(f"SLURM output log: {Path(RUNDIR) / 'myout'}")
                log(f"SLURM error log:  {Path(RUNDIR) / 'err2.out'}")
                log(f"SCHISM abort:     {Path(RUNDIR) / 'outputs' / 'fatal.error'}")
                log("Fix the input, then re-run:")
                log("  stofs-ak --run --phase run --only submit_run --config <cfg>")
                sys.exit(1)

            if exit_code > 0:
                # Non-zero exit but no diagnostic detail found (unexpected).
                log(f"WARNING: job {job_id} exited with code {exit_code} and "
                    f"no diagnostic detail was found.")
                log("This is likely a time-limit, node failure, or OOM.")
                log("Resubmitting from hotstart.nc (full month re-run).")
                previous_step = -1
                _clean_outputs()
                submit("run_test")
                continue

            previous_step = -1
            log(f"{RUN_JOBNAME}: not in queue and run incomplete — resubmitting "
                f"from hotstart.nc (full month re-run).")
            _clean_outputs()
            submit("run_test")

    log(f"{RUN_JOBNAME}: run completed successfully.")
    # Final diagnostic pass: the last output stack is only 'complete' now that
    # the run has finished (no out2d_{N+1} will ever appear).
    dispatch_diag_plots(run_finished=True)
    combine_and_chain()
    log(f"=== auto_hotstart for {MONTH} done ===")


if __name__ == "__main__":
    main()
